Release based deployment workflows.

diff --git a/.github/workflows/deploy_development.yml b/.github/workflows/deploy_development.yml
--- a/.github/workflows/deploy_development.yml
+++ b/.github/workflows/deploy_development.yml
@@ -1,25 +1,32 @@
 name: deploy_development
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: 'Version number'
-        required: true 
-        default: ''
-        type: string
+  release:
+    types: [prereleased]
 env:
   MAJORVERSION: ''
   COMPONENT_NAME: ${{ github.event.repository.name }}
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@v4
-    - name: Get version from input
-      run: echo "VERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
-      env: 
-        GITHUB_BRANCH: ${{ github.event.inputs.version }}
+    - name: 'Get Version'
+      id: get_version
+      uses: battila7/get-version-action@v2
+    - name: 'Check for correct naming convention'
+      if: ${{ !steps.get_version.outputs.is-semver }}
+      run: |
+        echo "::error title=Bad version format::The version specified does not follow semantic versioning"
+        exit 1
+    - name: Get version from tag
+      run: echo "VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV
+    - name: Check that the builder file exists
+      if: ${{ hashFiles(format('builder/versions/{0}.{1}.json', github.event.repository.name, steps.get_version.outputs.version-without-v)) == '' }}
+      run: |
+        echo "::error file=builder/versions,title=Missing builder file::The builder file for $VERSION is missing from builder/versions"
+        exit 1
     - name: Display version install
       run: echo "Installing dev version ${VERSION}"
 
